// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RecordEmployeeData.Models;

namespace RecordEmployeeData.Migrations
{
    [DbContext(typeof(RecordEmployeeDataContext))]
    partial class RecordEmployeeDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RecordEmployeeData.Models.EmployeeData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AppointmentType");

                    b.Property<int?>("BirthPlace");

                    b.Property<int?>("CentralAdministration");

                    b.Property<DateTime?>("CurrentJobDate");

                    b.Property<DateTime?>("DecisionDate");

                    b.Property<string>("DecisionNumber");

                    b.Property<string>("EmployeeAddress");

                    b.Property<string>("EmployeeName");

                    b.Property<int?>("EmployeeStatus");

                    b.Property<int?>("FanaticalDegree");

                    b.Property<int?>("Gender");

                    b.Property<int?>("Governorate");

                    b.Property<string>("IDNumber");

                    b.Property<string>("IssuerCode");

                    b.Property<int?>("JobGroup");

                    b.Property<int?>("JobTitle");

                    b.Property<DateTime?>("LastFinancialDisclosure");

                    b.Property<string>("LastQualifiedCode");

                    b.Property<DateTime?>("LastQualifiedDate");

                    b.Property<DateTime?>("LevelDate");

                    b.Property<string>("MotherName");

                    b.Property<int?>("Nationality");

                    b.Property<DateTime?>("ReceiptDate");

                    b.Property<DateTime?>("ReleaseDate");

                    b.Property<int?>("Religion");

                    b.Property<int?>("SectionCenter");

                    b.Property<DateTime?>("SeniorityHistoryDate");

                    b.Property<int?>("SocialStatus");

                    b.Property<int?>("Specialization");

                    b.Property<int?>("SubAdministration");

                    b.Property<string>("TelephoneNumber");

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
